apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-esp
  labels:
    config-type: esp 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: <NFS_SERVICE_IP>
    path: /hpcc-config/esp
