apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-esp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      config-type: esp
