apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-roxie
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      config-type: roxie
