apiVersion: v1
kind: ReplicationController
metadata:
  name: dali-rc
spec:
  replicas: 1
  selector:
    app: dali
  template:
    metadata:
      labels:
        app: dali
    spec:
      containers:
        - name: dali
          image: "hpccsystems/platform-ce:latest"
          ports:
            - containerPort: 8010
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/HPCCSystems
              name: config
          command:
            - /tmp/start_hpcc.sh
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-default

