apiVersion: v1
kind: Service
metadata: 
  name: esp
  labels: 
    app: esp
spec: 
  ports: 
    - name: esp
      protocol: TCP
      port: 8010
      targetPort: 8010
  selector: 
    app: esp
  type: LoadBalancer
