apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: hpccsystems/nfs-server:latest
        command:
          - /usr/local/bin/run_nfs.sh
        args:
          - /hpcc-config
          - /hpcc-data
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /hpcc-config
            name: hpcc-config
          - mountPath: /hpcc-data
            name: hpcc-data
      volumes:
        - name: hpcc-config
          awsElasticBlockStore:
            volumeID: <VOLUME_CONF>
            fsType: ext4
        - name: hpcc-data
          awsElasticBlockStore:
            volumeID: <VOLUME_ROXIE>
            fsType: ext4
