apiVersion: v1
kind: PersistentVolume
metadata:
  name: roxie-data-<INDEX>
spec:
  capacity:
    storage: <ROXIE_VOLUME_SIZE>Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: <NFS_SERVICE_IP>
    path: /roxie-data-<INDEX>
