apiVersion: v1
kind: Service
metadata: 
  name: roxie<INDEX>
  labels: 
     app: roxie<INDEX>
spec: 
  ports: 
    - name: roxie<INDEX>
      protocol: TCP
      port: 9876
      targetPort: 9876 
    - name: dfs
      protocol: TCP
      port: 7100
      targetPort: 7100
  selector: 
     app: roxie<INDEX>
  type: LoadBalancer
