apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app: test
spec:  # specification of the pod’s contents
  restartPolicy: Never
  containers:
    - name: test
      image: "hpccsystems/ansible-ce:latest"
      securityContext:
        privileged: true
      stdin: true
      tty: true
